"""
Department B1 — Proteasome (C-terminal proxy)

Biological hypothesis
---------------------
Peptides whose C-terminal residue is frequently observed at the C-terminus of
MHC-I ligands are more likely to be generated by proteasomal cleavage.

Computation logic
-----------------
This module uses a simple heuristic based only on the last amino acid of
candidate.peptide_mut:

- favored C-terminal residues (mostly hydrophobic / aromatic): positive score
- neutral residues: near-neutral score
- disfavored residues (especially strongly charged/polar in this simplified
  proxy): negative score

The score is intentionally simple, deterministic, and interpretable.
It does NOT model:
- upstream sequence context,
- exact cleavage site prediction,
- cleavage kinetics,
- constitutive vs immunoproteasome differences.

Limitations
-----------
The peptide C-terminus alone is only a coarse proxy for proteasomal generation.
A favorable score does not guarantee production of the peptide in vivo.
"""

from __future__ import annotations

import math

# Unique score name required by the project rules
_SCORE_NAME = "B_proteasome_cterm"

# Standard amino acids
_VALID_AA = set("ACDEFGHIKLMNPQRSTVWY")

# Simple qualitative groups for the C-terminal residue
# Favored: residues commonly compatible with MHC-I ligand C-termini in a simple proxy
_FAVORED = {"L", "I", "V", "F", "W", "Y", "M"}
# Neutral: tolerated but not especially favored in this simplified model
_NEUTRAL = {"A", "C", "G", "P", "T", "S", "N", "Q"}
# Disfavored: strongly charged/basic-acidic or less favorable in this coarse proxy
_DISFAVORED = {"D", "E", "K", "R", "H"}


def _safe_peptide_mut(candidate: object) -> str:
    """Safely extract candidate.peptide_mut as a stripped uppercase string."""
    peptide = getattr(candidate, "peptide_mut", "")
    if peptide is None:
        return ""
    if not isinstance(peptide, str):
        peptide = str(peptide)
    return peptide.strip().upper()


def _score_cterm_residue(residue: str) -> float:
    """
    Return a deterministic float score based only on the C-terminal residue.

    Scoring convention:
    - favored: +1.0
    - neutral: 0.0
    - disfavored: -1.0
    - invalid residue: -2.0
    """
    if residue not in _VALID_AA:
        return -2.0
    if residue in _FAVORED:
        return 1.0
    if residue in _NEUTRAL:
        return 0.0
    if residue in _DISFAVORED:
        return -1.0

    # Defensive fallback, should not happen with the groups above
    return -0.5


def get_score(candidate) -> tuple[str, float]:
    """
    Official Open-NeoVax module API.

    Parameters
    ----------
    candidate : Candidate
        Object expected to expose attribute `peptide_mut`.

    Returns
    -------
    tuple[str, float]
        (score_name, score_value)

    Failure policy
    --------------
    This function must never crash the pipeline. Any unexpected situation
    returns a documented penalty.
    """
    try:
        peptide = _safe_peptide_mut(candidate)

        # Edge case: missing or empty peptide
        if len(peptide) < 1:
            return _SCORE_NAME, -2.0

        cterm = peptide[-1]
        score = float(_score_cterm_residue(cterm))

        # Extra safety: forbid NaN / inf
        if not math.isfinite(score):
            return _SCORE_NAME, -2.0

        return _SCORE_NAME, score

    except Exception:
        # Fail gracefully, never block the pipeline
        return _SCORE_NAME, -2.0
