"""
Module B1 — Proteasome C-terminal proxy
Department B — Processing & cellular presentation

Biological hypothesis:
    The proteasome generates peptides through non-random cleavage.
    The C-terminal residue of a peptide reflects the proteasomal cleavage
    preferences. Peptides ending with hydrophobic or aromatic residues (e.g.
    L, I, V, F, Y, M) are more likely to result from actual proteasomal cuts,
    as these are over-represented at the C-terminus of HLA class I ligands in
    experimental data. Conversely, peptides ending with charged or polar
    residues (e.g. D, E, K, R) are less likely to be generated by the
    proteasome and receive a penalty.

Inputs:
    candidate.peptide_mut  (str) — mutated peptide sequence (8–11 aa expected)

Output:
    ("B_proteasome_cterm", float) — plausibility score based on C-terminal AA

Score interpretation:
    > 0  : favourable C-terminus, compatible with proteasomal generation
    = 0  : neutral C-terminus, no strong signal
    < 0  : unfavourable C-terminus, peptide less likely to be generated

    High score means: the C-terminal residue matches the hydrophobic/aromatic
    preference frequently observed at the C-terminus of experimentally validated
    HLA class I ligands — a plausible proteasomal cleavage product.

    Low score means: the C-terminal residue is charged (D, E, K, R), which is
    rarely observed at the C-terminus of HLA-I peptides in ligandome data,
    suggesting the proteasome is unlikely to produce this exact cleavage.

    Typical false positive: a peptide ending with V or L that was NOT generated
    by the proteasome but by another protease (e.g. cathepsins, signal peptidase).
    The C-terminal preference is a population-level bias, not a per-peptide
    guarantee. A high score does not confirm actual in-vivo generation.

    Critical question answered: the C-terminus is biologically relevant because
    the proteasome cleaves after hydrophobic/aromatic residues more frequently
    (documented in Kesmir et al. 2002, Tenzer et al. 2005). This residue defines
    the exact C-terminal end of the mature peptide before TAP transport and
    HLA loading — making it a necessary (though not sufficient) condition for
    presentation.

Limitations:
    - Only the last amino acid is considered; upstream context is ignored.
    - Immunoproteasome vs constitutive proteasome are not distinguished.
    - Preferences are based on qualitative literature consensus, not fitted data.
    - Peptide length is not modelled here (handled by module B4).
"""

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

SCORE_NAME = "B_proteasome_cterm"

# Residue preference table for C-terminal position of HLA-I ligands.
# Values are biologically motivated qualitative scores:
#   +1.0  strongly favoured  (hydrophobic / aromatic)
#    0.0  neutral
#   -1.0  disfavoured        (charged residues rarely at C-term)
#
# Source rationale: Kesmir et al. (2002), Tenzer et al. (2005) and review of
# SYFPEITHI / IEDB HLA-I ligand C-terminal distributions.
CTERM_PREFERENCE: dict[str, float] = {
    # Strongly favoured — hydrophobic / aromatic
    "L": 1.0,
    "I": 1.0,
    "V": 1.0,
    "F": 1.0,
    "Y": 1.0,
    "M": 0.8,
    "W": 0.6,
    # Moderately favoured — small / aliphatic
    "A": 0.4,
    # Neutral
    "G": 0.0,
    "S": 0.0,
    "T": 0.0,
    "C": 0.0,
    "P": 0.0,
    "N": 0.0,
    "Q": 0.0,
    "H": 0.0,
    # Disfavoured — charged residues
    "D": -1.0,
    "E": -1.0,
    "K": -1.0,
    "R": -1.0,
}

# Score returned for edge cases (empty peptide, invalid AA, etc.)
NEUTRAL_PENALTY: float = -0.5

# Standard amino acid alphabet (single-letter codes)
VALID_AMINO_ACIDS: frozenset[str] = frozenset(CTERM_PREFERENCE.keys())


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def get_score(candidate) -> tuple[str, float]:
    """
    Compute a proteasome C-terminal plausibility score.

    Parameters
    ----------
    candidate : Candidate
        Object exposing at least ``peptide_mut`` (str).

    Returns
    -------
    tuple[str, float]
        ("B_proteasome_cterm", score) where score is in [-1.0, +1.0] for
        valid inputs, or NEUTRAL_PENALTY for invalid / edge-case inputs.
    """
    score = _compute_cterm_score(candidate)
    return (SCORE_NAME, score)


# ---------------------------------------------------------------------------
# Internal logic
# ---------------------------------------------------------------------------


def _compute_cterm_score(candidate) -> float:
    """Extract C-terminal residue and look up preference score."""
    peptide = _extract_peptide(candidate)
    if peptide is None:
        return NEUTRAL_PENALTY

    cterm = _get_cterm(peptide)
    if cterm is None:
        return NEUTRAL_PENALTY

    return CTERM_PREFERENCE.get(cterm, NEUTRAL_PENALTY)


def _extract_peptide(candidate) -> str | None:
    """
    Safely retrieve peptide_mut from the candidate.

    Returns None if the attribute is missing, None, or not a string.
    """
    try:
        peptide = candidate.peptide_mut
    except AttributeError:
        return None

    if not isinstance(peptide, str):
        return None

    return peptide


def _get_cterm(peptide: str) -> str | None:
    """
    Return the last character of the peptide if it is a valid amino acid.

    Returns None for empty strings or non-standard residues.
    """
    if not peptide:
        return None

    last = peptide[-1].upper()
    if last not in VALID_AMINO_ACIDS:
        return None

    return last