"""
Module B1 — Proteasome C-terminal proxy
Department B — Processing & cellular presentation

Biological hypothesis:
    The proteasome generates peptides through non-random cleavage.
    The C-terminal residue of a peptide reflects proteasomal cleavage
    preferences. Peptides ending with hydrophobic or aromatic residues (e.g.
    L, I, V, F, Y, M) are more likely to result from actual proteasomal cuts,
    as these are over-represented at the C-terminus of HLA class I ligands in
    experimental data. Conversely, peptides ending with charged residues
    (e.g. D, E, K, R) are less likely to be generated by the proteasome and
    receive a penalty.

Inputs:
    candidate.peptide_mut  (str) — mutated peptide sequence (8–11 aa expected)

Output:
    ("B_proteasome_cterm", float) — plausibility score based on C-terminal AA

Score interpretation:
    > 0  : favourable C-terminus, compatible with proteasomal generation
    = 0  : neutral C-terminus, no strong signal
    < 0  : unfavourable C-terminus, peptide less likely to be generated

Limitations:
    - Only the last amino acid is considered; upstream context is ignored.
    - Immunoproteasome vs constitutive proteasome are not distinguished.
    - Preferences are based on qualitative literature consensus, not fitted data.
    - Peptide length is not modelled here (handled by module B4).
"""

from __future__ import annotations

from logic.types import Candidate

SCORE_NAME = "B_proteasome_cterm"

# Residue preference table for C-terminal position of HLA-I ligands.
# Values are biologically motivated qualitative scores:
#   +1.0  strongly favoured  (hydrophobic / aromatic)
#    0.0  neutral
#   -1.0  disfavoured        (charged residues rarely at C-term)
CTERM_PREFERENCE: dict[str, float] = {
    # Strongly favoured — hydrophobic / aromatic
    "L": 1.0,
    "I": 1.0,
    "V": 1.0,
    "F": 1.0,
    "Y": 1.0,
    "M": 0.8,
    "W": 0.6,
    # Moderately favoured — small / aliphatic
    "A": 0.4,
    # Neutral
    "G": 0.0,
    "S": 0.0,
    "T": 0.0,
    "C": 0.0,
    "P": 0.0,
    "N": 0.0,
    "Q": 0.0,
    "H": 0.0,
    # Disfavoured — charged residues
    "D": -1.0,
    "E": -1.0,
    "K": -1.0,
    "R": -1.0,
}

# Score returned for edge cases (empty peptide, invalid AA, etc.)
NEUTRAL_PENALTY: float = -0.5

# Standard amino acid alphabet (single-letter codes)
VALID_AMINO_ACIDS: frozenset[str] = frozenset(CTERM_PREFERENCE.keys())


def get_score(candidate: Candidate) -> tuple[str, float]:
    """Compute a proteasome C-terminal plausibility score."""
    score = _compute_cterm_score(candidate)
    return (SCORE_NAME, float(score))


def _compute_cterm_score(candidate: Candidate) -> float:
    """Extract the peptide C-terminus and return its preference score."""
    peptide = _extract_peptide(candidate)
    if peptide is None:
        return NEUTRAL_PENALTY

    cterm = _get_cterm(peptide)
    if cterm is None:
        return NEUTRAL_PENALTY

    return CTERM_PREFERENCE.get(cterm, NEUTRAL_PENALTY)


def _extract_peptide(candidate: Candidate) -> str | None:
    """Safely retrieve and normalize ``candidate.peptide_mut``."""
    try:
        peptide = candidate.peptide_mut
    except AttributeError:
        return None

    if not isinstance(peptide, str):
        return None

    peptide = peptide.strip()
    if not peptide:
        return None

    return peptide


def _get_cterm(peptide: str) -> str | None:
    """Return the valid C-terminal amino acid, or ``None`` if invalid."""
    last = peptide[-1].upper()
    if last not in VALID_AMINO_ACIDS:
        return None
    return last
