"""
Module B1 — Proteasome C-terminal proxy
Department B — Processing & cellular presentation

Biological hypothesis:
    The proteasome generates peptides through non-random cleavage.
    The C-terminal residue of a peptide reflects proteasomal cleavage
    preferences. Peptides ending with hydrophobic or aromatic residues (e.g.
    L, I, V, F, Y, M) are more likely to result from actual proteasomal cuts,
    as these are over-represented at the C-terminus of HLA class I ligands in
    experimental data. Conversely, peptides ending with charged residues
    (e.g. D, E, K, R) are less likely to be generated by the proteasome and
    receive a penalty.

Inputs:
    candidate.peptide_mut  (str) — mutated peptide sequence (8–11 aa expected)

Output:
    ("B_proteasome_cterm", float) — plausibility score based on C-terminal AA

Score interpretation:
    > 0  : favourable C-terminus, compatible with proteasomal generation
    = 0  : neutral C-terminus, no strong signal
    < 0  : unfavourable C-terminus, peptide less likely to be generated

    High score means: the C-terminal residue matches the hydrophobic/aromatic
    preference frequently observed at the C-terminus of experimentally validated
    HLA class I ligands — a plausible proteasomal cleavage product.

    Low score means: the C-terminal residue is charged (D, E, K, R), which is
    rarely observed at the C-terminus of HLA-I peptides in ligandome data,
    suggesting the proteasome is unlikely to produce this exact cleavage.

    Typical false positive: a peptide ending with V or L that was NOT generated
    by the proteasome but by another protease (e.g. cathepsins, signal peptidase).
    The C-terminal preference is a population-level bias, not a per-peptide
    guarantee. A high score does not confirm actual in-vivo generation.

    Critical question answered: the C-terminus is biologically relevant because
    the proteasome cleaves after hydrophobic/aromatic residues more frequently
    (documented in Kesmir et al. 2002, Tenzer et al. 2005). This residue defines
    the exact C-terminal end of the mature peptide before TAP transport and
    HLA loading — making it a necessary (though not sufficient) condition for
    presentation.

Limitations:
    - Only the last amino acid is considered; upstream context is ignored.
    - Immunoproteasome vs constitutive proteasome are not distinguished.
    - Preferences are based on qualitative literature consensus, not fitted data.
    - Peptide length is not modelled here (handled by module B4).
"""

from __future__ import annotations

from logic.types import Candidate

SCORE_NAME = "B_proteasome_cterm"

# Table de préférence des résidus pour la position C-terminale des ligands HLA-I.
# Les valeurs sont des scores qualitatifs biologiquement motivés :
#    +1.0  fortement favorisé  (hydrophobe / aromatique)
#    0.0   neutre
#    -1.0  défavorisé
#    (les résidus chargés sont rarement présents à la fin du C-term)
CTERM_PREFERENCE: dict[str, float] = {
    # Résidus fortement favorisés — hydrophobes / aromatiques
    "L": 1.0,
    "I": 1.0,
    "V": 1.0,
    "F": 1.0,
    "Y": 1.0,
    "M": 0.8,
    "W": 0.6,
    # Résidus modérément favorisés — petits / aliphatiques
    "A": 0.4,
    # Neutre
    "G": 0.0,
    "S": 0.0,
    "T": 0.0,
    "C": 0.0,
    "P": 0.0,
    "N": 0.0,
    "Q": 0.0,
    "H": 0.0,
    # Résidus défavorisés — chargés (rarement à la fin de C-term)
    "D": -1.0,
    "E": -1.0,
    "K": -1.0,
    "R": -1.0,
}

# Score retourné pour les cas particuliers (peptide vide, AA non valides, etc.)
NEUTRAL_PENALTY: float = -0.5

# Alphabet standard des acides aminés (codes à une lettre)
VALID_AMINO_ACIDS: frozenset[str] = frozenset(CTERM_PREFERENCE.keys())


# Fonction principale pour obtenir le score du peptide
def get_score(candidate: Candidate) -> tuple[str, float]:
    """Compute a proteasome C-terminal plausibility score."""
    score = _compute_cterm_score(candidate)
    return (SCORE_NAME, float(score))


# Fonction interne pour extraire le score du C-terminal
def _compute_cterm_score(candidate: Candidate) -> float:
    """Extract the peptide C-terminus and return its preference score."""
    peptide = _extract_peptide(candidate)
    if peptide is None:
        return NEUTRAL_PENALTY

    cterm = _get_cterm(peptide)
    if cterm is None:
        return NEUTRAL_PENALTY

    # Récupère le score pour le C-terminal (AA du peptide)
    return CTERM_PREFERENCE.get(cterm, NEUTRAL_PENALTY)


# Fonction interne pour extraire le peptide muté
def _extract_peptide(candidate: Candidate) -> str | None:
    """Safely retrieve and normalize ``candidate.peptide_mut``."""
    try:
        peptide = candidate.peptide_mut
    except AttributeError:
        return None

    if not isinstance(peptide, str):
        return None

    peptide = peptide.strip()
    if not peptide:
        return None

    return peptide


# Fonction pour obtenir le C-terminal du peptide
def _get_cterm(peptide: str) -> str | None:
    """Return the valid C-terminal amino acid, or ``None`` if invalid."""
    last = peptide[-1].upper()
    if last not in VALID_AMINO_ACIDS:
        return None
    return last
